name: 'Get & cache dependencies'
description: 'Get code and cache dependencies'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used or not.'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id : install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'

      run: |
       npm ci
       echo "cache=${{ inputs.caching}}" >> $GITHUB_OUTPUT
      shell: bash